# This is a basic workflow to help you get started with Actions

name: Docs to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths: ['**.md']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "convert_to_pdf"
  convert_to_pdf: 
    name: Build PDF
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Building PDF...
        
      # We must checkout the latest version of the code to get a copy of all .md files
      - name: Checkout Code
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - name: Create .pdfs
        uses: scottypate/md-to-pdf@v0.1.1
        env:
          # Use this parameter to determine where the generated .pdf(s) will be stored.
          PDF_DIR: './pdfs'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          # The token is built in to actions. No config required.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Add .pdf files.
          PULL_REQUEST_TITLE: Add .pdf files.
          PULL_REQUEST_BRANCH: pdf-add
          PULL_REQUEST_BODY: Here are the .pdf files you requested :wave:.
          PULL_REQUEST_REVIEWERS: scottypate
          
